[package]
name = "Bouncer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.27.1"
sysinfo = "0.29.10"
users = "0.11.0"
